In [14]:
import numpy as np

In [15]:
A = [[1,2],[2,3]]
B = [[2,3],[3,4]]

In [19]:
dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

[[1, 2], [2, 3]]

In [17]:
B

[[2, 3], [3, 4]]

In [6]:
2*3

6

In [7]:
2*3

6

In [8]:
1+1

2

In [9]:
2+2+2

6

In [10]:
import math

In [11]:
math.log(2)

0.6931471805599453

In [25]:
X = np.random.randn(3,4)

In [26]:
X

array([[ 0.94451441, -0.50367719,  1.54142496, -0.48541449],
       [-1.11107467, -1.35122909, -0.03528847, -0.46639419],
       [ 0.8763313 , -1.10785483, -1.1332181 ,  1.010197  ]])

In [27]:
X[1][2]

-0.03528846544346109

In [28]:
X[0][3]

-0.48541448711115676

In [29]:
X[1,2]

-0.03528846544346109

In [30]:
X[0,3]

-0.48541448711115676

In [35]:
X[0:2,0:2]

array([[ 0.94451441, -0.50367719],
       [-1.11107467, -1.35122909]])

In [37]:
X[1:3,1:3]

array([[-1.35122909, -0.03528847],
       [-1.10785483, -1.1332181 ]])

In [38]:
X[0:3,0:2]

array([[ 0.94451441, -0.50367719],
       [-1.11107467, -1.35122909],
       [ 0.8763313 , -1.10785483]])

In [33]:
name = "Tharun"
name[1:4]

'har'

In [31]:
lis = [1,2,3,4]

In [36]:
lis[1:3]

[2, 3]

In [22]:
A = np.array(A)
A

array([[1, 2],
       [2, 3]])

In [23]:
B = np.array(B)
B

array([[2, 3],
       [3, 4]])

In [6]:
C = np.dot(A,B)

In [7]:
C

array([[ 8, 11],
       [13, 18]])

In [18]:
A = [[1,2],[2,3]]
B = [[2,3],[3,4]]

In [19]:
A

[[1, 2], [2, 3]]

In [20]:
B

[[2, 3], [3, 4]]

In [21]:
[1,"A","B",2]

[1, 'A', 'B', 2]

In [22]:
[1,2,3,4]

[1, 2, 3, 4]

In [23]:
int('6')

6

In [ ]:
# int, string, float, list --> ndarray

In [8]:
A = np.array(A) # Explicit Type Casting

In [25]:
A

array([[1, 2],
       [2, 3]])

In [9]:
B = np.array(B) # np.array is constuctor --> list --> ndarray B --> object

In [12]:
(p,q) = B.shape

In [42]:
B.dtype

dtype('int64')

In [10]:
(m,n) = A.shape

In [13]:
if n==p:
    print(f"Matrix multiplcation of A and B is possible")

Matrix multiplcation of A and B is possible


In [44]:
C = np.zeros((m,q),dtype=np.int64) # in float64
C

array([[0, 0],
       [0, 0]])

In [53]:
C = np.dot(A,B)
C
# 100-200 cpu clocks

array([[ 8, 11],
       [13, 18]])

In [ ]:
torch 
2 gpu clocks

In [56]:
for row in range(m):
    for column in range(q):
        C[row,column] = np.multiply(A[row],B[column]).sum()
C

"""
1*2+1*2

Sequentially
1. row -0
2. column -0
3. one operaton
4. row =0
5. column = 1
6. second operation
7. row = 1
8. column = 0
9. thrid operation
10. row = 1
11. column = 1
12. fourth operation

---> m*q number of operations sequentially
"""

'\nSequentially\n1. row -0\n2. column -0\n3. one operaton\n4. row =0\n5. column = 1\n6. second operation\n7. row = 1\n8. column = 0\n9. thrid operation\n10. row = 1\n11. column = 1\n12. fourth operation\n'

In [1]:
for row in range(m):
    for column in range(q):
        C[row,column] = 0
        for k in range(n):
            C[row,column] = C[row,column]+(A[row,k]*B[k,column])
C
"""
8 sequenctial operations
Total number of iterations -> m * q * n 
Time Complexity -===> O(n~3) in general
Time Complexity -===> O(m*q*n) for my matrix multiplcation of A (m,n) and B (n,q). In General if we have m = n = q Trivial condition ==> O(n*n*n) ==> O(n~3)
"""

NameError: name 'm' is not defined

In [ ]:
A(1024,512) * B(512,1024)

1024*512*1024 = 

Number of multiplcations => 1024*512*1024
Number of additions => 1024*512*1024

Total number of cpu clocks =  2 * 1024 * 512 * 1024