In [2]:
import numpy as np

In [3]:
A = [[1,2],[2,3]]
B = [[2,3],[3,4]]

In [4]:
A

[[1, 2], [2, 3]]

In [5]:
B

[[2, 3], [3, 4]]

In [6]:
2*3

6

In [7]:
2*3

6

In [8]:
1+1

2

In [9]:
2+2+2

6

In [10]:
import math

In [11]:
math.log(2)

0.6931471805599453

In [15]:
A = np.array(A)

In [14]:
B = np.array(B)

In [16]:
C = np.dot(A,B)

In [17]:
C

array([[ 8, 11],
       [13, 18]])

In [18]:
A = [[1,2],[2,3]]
B = [[2,3],[3,4]]

In [19]:
A

[[1, 2], [2, 3]]

In [20]:
B

[[2, 3], [3, 4]]

In [21]:
[1,"A","B",2]

[1, 'A', 'B', 2]

In [22]:
[1,2,3,4]

[1, 2, 3, 4]

In [23]:
int('6')

6

In [ ]:
# int, string, float, list --> ndarray

In [24]:
A = np.array(A) # Explicit Type Casting

In [25]:
A

array([[1, 2],
       [2, 3]])

In [26]:
B = np.array(B) # np.array is constuctor --> list --> ndarray B --> object

In [32]:
(p,q) = B.shape

In [42]:
B.dtype

dtype('int64')

In [33]:
(m,n) = A.shape

In [39]:
if n==p:
    print(f"Matrix multiplcation of A and B is possible")

Matrix multiplcation of A and B is possible


In [44]:
C = np.zeros((m,q),dtype=np.int64) # in float64
C

array([[0, 0],
       [0, 0]])

In [53]:
C = np.dot(A,B)
C
# 100-200 cpu clocks

array([[ 8, 11],
       [13, 18]])

In [ ]:
torch 
2 gpu clocks

In [56]:
for row in range(m):
    for column in range(q):
        C[row,column] = np.multiply(A[row],B[column]).sum()
C

"""
1*2+1*2

Sequentially
1. row -0
2. column -0
3. one operaton
4. row =0
5. column = 1
6. second operation
7. row = 1
8. column = 0
9. thrid operation
10. row = 1
11. column = 1
12. fourth operation

---> m*q number of operations sequentially
"""

'\nSequentially\n1. row -0\n2. column -0\n3. one operaton\n4. row =0\n5. column = 1\n6. second operation\n7. row = 1\n8. column = 0\n9. thrid operation\n10. row = 1\n11. column = 1\n12. fourth operation\n'

In [55]:
for row in range(m):
    for column in range(q):
        C[row,column] = 0
        for k in range(n):
            C[row,column] = C[row,column]+(A[row,k]*B[k,column])
C
"""
8 sequenctial operations
Total number of iterations -> m * q * n 
Time Complexity -===> O(n~3) in general
Time Complexity -===> O(m*q*n) for my matrix multiplcation of A (m,n) and B (n,q). In General if we have m = n = q Trivial condition ==> O(n*n*n) ==> O(n~3)
"""

array([[ 8, 11],
       [13, 18]])

In [ ]:
A(1024,512) * B(512,1024)

1024*512*1024 = 

Number of multiplcations => 1024*512*1024
Number of additions => 1024*512*1024

Total number of cpu clocks =  2 * 1024 * 512 * 1024